### ISSUE TITLE
builtin load function

### ISSUE THREAD

**Issue by podhmo** [podhmo/zenmai#1]

**Comment by podhmo** [comment]
the way of resolving relative path if loading data is such as below, base path is the path of nested file.

structure

```bash
.
├── data
│   └── pallete.yaml
├── main.yaml
└── primitive
    └── cmyk.yaml
```

main.yaml

```yaml
pallete:
  $load: "./data/pallete.yaml"
```

data/pallete.yaml

```yaml
palette:
  type: object
  properties:
    name:
      type: string
    color:
      $load: "../primitive/cmyk.yaml"
      # base path is ./data/pallete.yaml
```

primitive/cmyk.yaml

```yaml
color:
  type: string
  enum:
    - C
    - M
    - Y
    - K
```

**Comment by podhmo** [comment]
also support json reference (optional)

**Comment by podhmo** [comment]
output is 

```yaml
pallete:
  palette:
    type: object
    properties:
      name:
        type: string
      color:
        color:
          type: string
          enum:
            - C
            - M
            - Y
            - K
```
