### ISSUE TITLE
$load with keyword arguments

### ISSUE THREAD

**Issue by podhmo** [podhmo/zenmai#14]

**Comment by podhmo** [comment]
a.yaml

```yaml
b:
  $let:
    mydata: {value: 10}
  body:
    $load:  ./b.yaml
    data: {$get: mydata}
```

b.yaml

```yaml
# need: data
name: b
data: {$get: data}
```

**Comment by podhmo** [comment]
output

```yaml
b:
  name: b
  data:
    value: 10
```
