### ISSUE TITLE
counter function

### ISSUE THREAD

**Issue by podhmo** [podhmo/zenmai#17]
```yaml
$let:
  c0: {$counter: 3}
  c1: {$counter: 0}
body:
  - {$c0: "item{:04}"}
  - {$c1}
  - {$c0: "item{:04}"}
  - {$c1}

output:
  - item0003
  - 0
  - item0004
  - 1
```
