### ISSUE TITLE
format functin

### ISSUE THREAD

**Issue by podhmo** [podhmo/zenmai#18]
```yaml
- $format: "{prefix}{number:04}"
  prefix: foo
  number: 0
- $format: "{prefix}{number:04}"
  prefix: foo
  number: 1
- $format: "{prefix}{number:04}"
  prefix: bar
  number: 0

output:
  - foo0000
  - foo0001
  - bar0000

```
