### ISSUE TITLE
$get with default value

### ISSUE THREAD

**Issue by podhmo** [podhmo/zenmai#19]
```yaml
$let:
  person:
    name: foo
body:
  - {$get: person}
  - {$get: "person#/name"}
  - {$get: "person#/age", default: 0}


output:
  - name: foo
  - foo
  - 0
```
