### ISSUE TITLE
$format function enhancement

### ISSUE THREAD

**Issue by podhmo** [podhmo/zenmai#20]
before:

target is only string

```yaml
{$format: "foo{bar}", bar: "boo"}
# => fooboo
```
after:

```yaml
$let:
  items:
    app: "{prefix}-app"
    batch: "{prefix}-batch"
body:
  $format: {$get: items}
  prefix: dev

output:
  app: dev-app
  batch: dev-batch
...

```
