### ISSUE TITLE
when and unless syntax

### ISSUE THREAD

**Issue by podhmo** [podhmo/zenmai#22]

**Comment by podhmo** [comment]
```yaml
# 00when.yaml
db:
  $when: {$get: "data#/usedb"}
  body: localhost:27000/foo
mail:
  $when: {$get: "data#/usemail"}
  body:
    {$format: "http://{me}@bar.ne.jp", me: {$get: "data#/me"}}
```

```bash
zenmai 00when.yaml --data "data.yaml#/local" > 00when.local.yaml
zenmai 00when.yaml --data "data.yaml#/dev" > 00when.dev.yaml
```

```yaml
#data.yaml
local:
  usedb: true
  usemail: false
  me: foo
dev:
  usedb: true
  usemail: true
  me: foo
```


```yaml
# 00when.local.yaml
db: localhost:27000/foo
```

```yaml
# 00when.dev.yaml
db: localhost:27000/foo
mail: http://foo@bar.ne.jp
```
