### ISSUE TITLE
builtin chain function

### ISSUE THREAD

**Issue by podhmo** [podhmo/zenmai#4]
e.g.

```yaml
$suffix:
  $suffix:
    person:
      name: foo
  suffix: +
suffix: +
```

to

```yaml
$chain:
  person:
    name: foo
    age: 20
body:
  - $suffix: {suffix: +}
  - $suffix: {suffix: +}
```
