### ISSUE TITLE
quote

### ISSUE THREAD

**Issue by podhmo** [podhmo/zenmai#5]
maybe

```
$action
```

```
$$quoted
```

**Comment by podhmo** [comment]
```yaml
body:
  $quote:
    $load:  foo.yaml

output:
  body:
    $load: foo.yaml
```

```yaml
body:
    $$load:  foo.yaml

output:
  body:
    $load: foo.yaml
```
