### ISSUE TITLE
template function using jinja2

### ISSUE THREAD

**Issue by podhmo** [podhmo/zenmai#6]

**Comment by podhmo** [comment]
```yaml
$let:
  item-template:
    $jinja2_template: |
      items:
        {% for i in nums %}
        - {{prefix|default("no")}}.{{i}}
        {% endfor %}
body:
  listing:
    $item-template:
      nums: [1,2,3]
```

output

```yaml
listing:
  items:
  - no.1
  - no.2
  - no.3
```
